"""
Daily Market Briefing Script
Fetches headlines from CNN Business, CNBC, Motley Fool, Forbes
Summarizes via Claude API and emails via Gmail SMTP
"""

import feedparser
import anthropic
import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

# ── RSS Feeds ────────────────────────────────────────────────────────────────
FEEDS = {
    "CNN Business":  "https://rss.cnn.com/rss/money_latest.rss",
    "CNBC":          "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    "Motley Fool":   "https://www.fool.com/feeds/index.aspx",
    "Forbes":        "https://www.forbes.com/investing/feed2/",
}

MAX_ARTICLES_PER_SOURCE = 8   # how many headlines to pull per source


def fetch_headlines() -> dict[str, list[dict]]:
    """Pull latest headlines from each RSS feed."""
    results = {}
    for source, url in FEEDS.items():
        try:
            feed = feedparser.parse(url)
            articles = []
            for entry in feed.entries[:MAX_ARTICLES_PER_SOURCE]:
                articles.append({
                    "title":   entry.get("title", ""),
                    "summary": entry.get("summary", "")[:300],
                    "link":    entry.get("link", ""),
                })
            results[source] = articles
            print(f"✓ {source}: {len(articles)} articles")
        except Exception as e:
            print(f"✗ {source}: {e}")
            results[source] = []
    return results


def build_prompt(headlines: dict[str, list[dict]]) -> str:
    """Format headlines into a prompt for Claude."""
    today = datetime.now().strftime("%A, %d %B %Y")
    lines = [f"Today is {today}. Below are the latest headlines from major financial news sources.\n"]

    for source, articles in headlines.items():
        lines.append(f"\n## {source}")
        for a in articles:
            lines.append(f"- {a['title']}")
            if a["summary"]:
                lines.append(f"  {a['summary'][:200]}")

    lines.append("""
─────────────────────────────────────────────────
Based on the above, write a concise daily market briefing for an investor focused on US equities and global macro trends. Structure it exactly like this:

**📊 MARKET MOOD** (1–2 sentences: overall sentiment today — risk-on/off, bullish/bearish tone)

**🔑 TOP 5 STORIES TO WATCH**
For each story: bold headline, then 2–3 sentences on what it means for markets/investors.

**📈 SECTORS & STOCKS IN FOCUS**
Which sectors or individual stocks are getting attention today and why.

**⚠️ RISKS & WATCH LIST**
Key risks, macro concerns, or events to monitor this week.

**💡 BOTTOM LINE**
One sharp paragraph — what should an investor keep in mind going into today's session?

Keep the total length under 600 words. Be direct, no fluff.
""")
    return "\n".join(lines)


def get_briefing_from_claude(prompt: str) -> str:
    """Call Claude API to generate the briefing."""
    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1200,
        messages=[{"role": "user", "content": prompt}],
    )
    return message.content[0].text


def build_html_email(briefing_text: str) -> str:
    """Wrap the briefing in a clean HTML email."""
    today = datetime.now().strftime("%A, %d %B %Y")

    # Convert markdown-ish bold (**text**) to <strong>
    import re
    html_body = briefing_text
    html_body = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', html_body)
    html_body = html_body.replace('\n\n', '</p><p>').replace('\n', '<br>')

    return f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #f5f5f5; margin: 0; padding: 20px; }}
  .container {{ max-width: 680px; margin: 0 auto; background: #ffffff; border-radius: 8px;
                box-shadow: 0 2px 8px rgba(0,0,0,0.08); overflow: hidden; }}
  .header {{ background: #0a2540; color: white; padding: 24px 32px; }}
  .header h1 {{ margin: 0; font-size: 22px; font-weight: 700; letter-spacing: 0.5px; }}
  .header p  {{ margin: 6px 0 0; font-size: 13px; opacity: 0.7; }}
  .body {{ padding: 28px 32px; color: #1a1a2e; font-size: 15px; line-height: 1.7; }}
  .body p {{ margin: 0 0 14px; }}
  .footer {{ background: #f9f9f9; border-top: 1px solid #eee; padding: 14px 32px;
             font-size: 12px; color: #999; text-align: center; }}
  strong {{ color: #0a2540; }}
</style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📰 Daily Market Briefing</h1>
      <p>{today} &nbsp;|&nbsp; Sources: CNN Business · CNBC · Motley Fool · Forbes</p>
    </div>
    <div class="body">
      <p>{html_body}</p>
    </div>
    <div class="footer">
      Generated by Claude AI &nbsp;·&nbsp; For informational purposes only — not financial advice.
    </div>
  </div>
</body>
</html>
"""


def send_email(subject: str, html_body: str):
    """Send the briefing email via Gmail SMTP."""
    sender   = os.environ["GMAIL_SENDER"]       # your Gmail address
    password = os.environ["GMAIL_APP_PASSWORD"]  # Gmail App Password (not your login password)
    receiver = os.environ["GMAIL_RECEIVER"]      # where to send (can be same as sender)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = sender
    msg["To"]      = receiver
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender, password)
        server.sendmail(sender, receiver, msg.as_string())
    print(f"✓ Email sent to {receiver}")


def main():
    print("── Fetching headlines ──────────────────")
    headlines = fetch_headlines()

    print("── Generating briefing with Claude ─────")
    prompt   = build_prompt(headlines)
    briefing = get_briefing_from_claude(prompt)

    today   = datetime.now().strftime("%d %b %Y")
    subject = f"📊 Market Briefing — {today}"
    html    = build_html_email(briefing)

    print("── Sending email ───────────────────────")
    send_email(subject, html)
    print("✅ Done!")


if __name__ == "__main__":
    main()
