import feedparser
import anthropic
import smtplib
import os
import re
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

FEEDS = {
    "CNN Business": "https://rss.cnn.com/rss/money_latest.rss",
    "CNBC": "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    "Motley Fool": "https://www.fool.com/feeds/index.aspx",
    "Forbes": "https://www.forbes.com/investing/feed2/",
}

def fetch_headlines():
    results = {}
    for source, url in FEEDS.items():
        try:
            feed = feedparser.parse(url)
            articles = []
            for entry in feed.entries[:8]:
                articles.append({
                    "title": entry.get("title", ""),
                    "summary": entry.get("summary", "")[:300],
                })
            results[source] = articles
            print("OK " + source)
        except Exception as e:
            print("FAIL " + source + " " + str(e))
            results[source] = []
    return results

def build_prompt(headlines):
    today = datetime.now().strftime("%A, %d %B %Y")
    lines = ["Today is " + today + ". Latest headlines:\n"]
    for source, articles in headlines.items():
        lines.append("## " + source)
        for a in articles:
            lines.append("- " + a["title"])
    lines.append("Write a daily market briefing for a US equity investor. Use this structure: MARKET MOOD: 1-2 sentences on overall sentiment. TOP 5 STORIES: headline and 2-3 sentences on market impact each. SECTORS IN FOCUS: which sectors or stocks are moving and why. RISKS TO WATCH: key risks and macro concerns. BOTTOM LINE: one paragraph summary. Under 600 words.")
    return "\n".join(lines)

def get_briefing(prompt):
    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1200,
        messages=[{"role": "user", "content": prompt}],
    )
    return message.content[0].text

def make_html(briefing_text):
    today = datetime.now().strftime("%A, %d %B %Y")
    body = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', briefing_text)
    body = body.replace('\n\n', '</p><p>').replace('\n', '<br>')
    style = "font-family:Arial,sans-serif;max-width:680px;margin:0 auto;"
    header_style = "background:#0a2540;color:white;padding:24px 32px;"
    body_style = "padding:28px 32px;color:#1a1a2e;font-size:15px;line-height:1.7;"
    footer_style = "background:#f9f9f9;border-top:1px solid #eee;padding:14px 32px;font-size:12px;color:#999;text-align:center;"
    html = "<div style='" + style + "'>"
    html += "<div style='" + header_style + "'><h1 style='margin:0;font-size:22px;'>Daily Market Briefing</h1>"
    html += "<p style='margin:6px 0 0;font-size:13px;opacity:0.7;'>" + today + " | CNN Business · CNBC · Motley Fool · Forbes</p></div>"
    html += "<div style='" + body_style + "'><p>" + body + "</p></div>"
    html += "<div style='" + footer_style + "'>Generated by Claude AI · Not financial advice.</div>"
    html += "</div>"
    return html

def send_email(subject, html_body):
    sender = os.environ["GMAIL_SENDER"]
    password = os.environ["GMAIL_APP_PASSWORD"]
    receiver = os.environ["GMAIL_RECEIVER"]
    all_receivers = [receiver, "drvikneshwaran.arumugam@gmail.com", "chandraganesan94@gmail.com"]
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = ", ".join(all_receivers)
    msg.attach(MIMEText(html_body, "html"))
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender, password)
        server.sendmail(sender, all_receivers, msg.as_string())
    print("Email sent to " + str(all_receivers))

def main():
    print("Fetching headlines...")
    headlines = fetch_headlines()
    print("Generating briefing...")
    prompt = build_prompt(headlines)
    briefing = get_briefing(prompt)
    today = datetime.now().strftime("%d %b %Y")
    subject = "Market Briefing - " + today
    html = make_html(briefing)
    print("Sending email...")
    send_email(subject, html)
    print("Done!")

if __name__ == "__main__":
    main()
